debug: False

servers:
    - name: example
      host: irc.example.com
      port: 6667
      ssl: False
      nick: brobot
      nickserv_password: 
      admins:
          - you
          - someone
      channels:
          - '#example'

command_plugins:
    PRIVMSG:
    PUBMSG:
        - path: users.UsersPlugin
          commands:
              - users
    BOTH:
        - path: bot.BotPlugin
          commands:
              - bot
        - path: admin.JoinPlugin
          commands:
              - join
        - path: admin.PartPlugin
          commands:
              - part
        - path: admin.QuitPlugin
          commands:
              - quit
        - path: admin.ExitPlugin
          commands:
              - exit
        - path: commands.CommandsPlugin
          commands:
              - commands
              - help
        - path: version.VersionPlugin
          commands:
              - version
        - path: reboot.RebootPlugin
          commands:
              - reboot
    

event_plugins:
    - name: PUBMSG
      plugins:
          - urititle.URITitlePlugin

plugin_path: plugins
data_path: data
log_filename: brobot.log
pid_filename: brobot.pid
command_prefix: '!'
version_string: brobot v0.95
